# Site settings
title: Weathering Brainstorms
email: alkevintan@gmail.com
description: >-
  A collection of thoughts
baseurl: "/aktan.github.io"
url: "https://alkevintan.github.io"
twitter_username: cpnbrainstorm
linkedin_username: alkevintan
github_username: alkevintan

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - .jekyll-cache/
  - .sass-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
